version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mche19p49r96"
s3_prefix = "sam-hello-world"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
