form527map = {
    'Date of Claim': 'claim_date',
    'Vet Name': 'name',
    'Vet SSN': 'SSN',
    'Vet DOB': 'DOB',
    'Previous Claim Y': 'previus_claim.true',
    'Previous Claim N': 'previus_claim.false',
    'VA File Number': 'va_file_number',
    'Vet Mailing Address': 'mailing_address',
    'Vet City': 'mailing_address_city',
    'Vet State': 'mailing_address_state',
    'Vet Phone Number': 'telephon_number',
    'Disability': 'disabilities.description',
    'Date Disability Began': 'disabilities.date_began',
    'Name of Location VA Center': 'medical_centers.location',
    'Dates of Treament': 'medical_centers.treatment_date',
    'Army': 'branch_of_service.army',
    'Navy': 'branch_of_service.navy',
    'Marine Corps': 'branch_of_service.marine_corps',
    'Space Force': 'branch_of_service.space_force',
    'Air Force': 'branch_of_service.air_force',
    'Coast Guard': 'branch_of_service.coast_guard',
    'Active Service Date': 'veteran_service_entry_date',
    'Active Service Release Date': 'release_date',
    'Service Number': 'service_number',
    'Place of Separation': 'last_separation',
    'POW Y': 'pow.true',
    'POW N': 'pow.false',
    '14A Y': 'special_pension.true',
    '14A N': 'special_pension.false',
    '14B Y': 'recently_hospitalized.true',
    '14B N': 'recently_hospitalized.false',
    '16A Y': 'employed.true',
    '16A N': 'employed.false',
    '16C Y': 'self_employed.true',
    '16C N': 'self_employed.false',
    '17A Y': 'nursing_home.true',
    '17A N': 'nursing_home.false',
    'Married': 'marital_status.married',
    'Divorced': 'marital_status.divorced',
    'Widowed': 'marital_status.widowed',
    'NM': 'marital_status.never_married',
    'Times Married': 'veteran_marriages.times_married',
    'Marriage Date': 'veteran_marriages.details0.date_of_marriage',
    'Spouse Name': 'veteran_marriages.details0.whom_married',
    'Type of Marriage': 'veteran_marriages.details0.type_of_marriage',
    'Marriage Ended': 'veteran_marriages.details0.how_marriage_ended',
    'Marriage Ended Date': 'veteran_marriages.details0.date_ended',
    'Times Spouse Married': 'spouse_marriages.times_married',
    'Spouse Marriage Date': 'spouse_marriages.details0.date_of_marriage',
    'Spouse Married Whom': 'spouse_marriages.details0.whom_married',
    'Spouse Type of Marriage': 'spouse_marriages.details0.type_of_marriage',
    'Spouse How Marriage Ended': 'spouse_marriages.details0.how_marriage_ended',
    'Spouse Date Marriage Ended': 'spouse_marriages.details0.date_ended',
    'Spouse DOB': 'spouse_dob',
    'Spouse SSN': 'spouse_ssn',
    '23C Y': 'spouse_veteran.true',
    '23C N': 'spouse_veteran.false',
    '23E Y': 'live_with_spouse.true',
    '23E N': 'live_with_spouse.false',
    'Spouse VA File Number': 'spouse_va_file_number',
    'Spouse Address': 'spouse_address',
    'Spouse City': 'spouse_address_city',
    'Spouse State': 'spouse_address_state',
    'Spouse Zip': 'spouse_address_zip',
    'SS Recip 1': 'ss_payments0.recepient',
    'SS Amount 1': 'ss_payments0.amount',
    'SS Recip 2': 'ss_payments1.recepient',
    'SS Amount 2': 'ss_payments1.amount',
    'A1': 'expenses0.person',
    'Paid To 1': 'expenses0.paid_to',
    'Purpose 1': 'expenses0.purpose',
    'Date 1': 'expenses0.date_paid',
    'Amount 1': 'expenses0.amount_paid',
    'A2': 'expenses1.person',
    'Paid To 2': 'expenses1.paid_to',
    'Purpose 2': 'expenses1.purpose',
    'Date 2': 'expenses1.date_paid',
    'Amount 2': 'expenses1.amount_paid',
    'A3': 'expenses2.person',
    'Paid To 3': 'expenses2.paid_to',
    'Purpose 3': 'expenses2.purpose',
    'Date 3': 'expenses2.date_paid',
    'Amount 3': 'expenses2.amount_paid',
    'A4': 'expenses3.person',
    'Paid To 4': 'expenses3.paid_to',
    'Purpose 4': 'expenses3.purpose',
    'Date 4': 'expenses3.date_paid',
    'Amount 4': 'expenses3.amount_paid',
    'A5': 'expenses4.person',
    'Paid To 5': 'expenses4.paid_to',
    'Purpose 5': 'expenses4.purpose',
    'Date 5': 'expenses4.date_paid',
    'Amount 5': 'expenses4.amount_paid',
    'A6': 'expenses5.person',
    'Paid To 6': 'expenses5.paid_to',
    'Purpose 6': 'expenses5.purpose',
    'Date 6': 'expenses5.date_paid',
    'Amount 6': 'expenses5.amount_paid',
}
ssn_inquiry_map = {
    'Premium Amount': 'premium_amount',
    'Monthly Benefit Credited Date 1': 'monthly_benefit0.date',
    'Monthly Benefit Credited Amount 1': 'monthly_benefit0.amount',
    'Monthly Benefit Credited Type 1': 'monthly_benefit0.type',
    'Monthly Benefit Credited Date 2': 'monthly_benefit1.date',
    'Monthly Benefit Credited Amount 2': 'monthly_benefit1.amount',
    'Monthly Benefit Credited Type 2': 'monthly_benefit1.type',
    'Monthly Benefit Credited Date 3': 'monthly_benefit2.date',
    'Monthly Benefit Credited Amount 3': 'monthly_benefit2.amount',
    'Monthly Benefit Credited Type 3': 'monthly_benefit2.type',
    'Monthly Benefit Credited Date 4': 'monthly_benefit3.date',
    'Monthly Benefit Credited Amount 4': 'monthly_benefit3.amount',
    'Monthly Benefit Credited Type 4': 'monthly_benefit3.type',
    'Monthly Benefit Credited Date 5': 'monthly_benefit4.date',
    'Monthly Benefit Credited Amount 5': 'monthly_benefit4.amount',
    'Monthly Benefit Credited Type 5': 'monthly_benefit4.type',
    'Monthly Benefit Credited Date 6': 'monthly_benefit5.date',
    'Monthly Benefit Credited Amount 6': 'monthly_benefit5.amount',
    'Monthly Benefit Credited Type 6': 'monthly_benefit5.type',
    'Monthly Benefit Credited Date 7': 'monthly_benefit6.date',
    'Monthly Benefit Credited Amount 7': 'monthly_benefit6.amount',
    'Monthly Benefit Credited Type 7': 'monthly_benefit6.type',
    'Monthly Benefit Credited Date 8': 'monthly_benefit7.date',
    'Monthly Benefit Credited Amount 8': 'monthly_benefit7.amount',
    'Monthly Benefit Credited Type 8': 'monthly_benefit7.type'
}
form8416map = {
    'Vet Name': 'name',
    'SSN First 3': 'SSN',
    'VA File Number': 'va_file_number',
    'Claimant Name': 'claimant_name',
    'Claimant Address': 'mailing_address',
    'Claimant City': 'mailing_address_city',
    'Claimant State': 'mailing_address_state',
    'Claimant Zip': 'mailing_address_zip',
    'Claimant Phone': 'telephone',
    'Claimant Sig': 'claimants_signature',
    'Month Signed': 'date_signed',
}
for i in range(1,19):
    form8416map['11. A Item '+str(i)] = 'expenses'+str(i-1)+'.purpose'
    form8416map['11. B Item '+str(i)] = 'expenses'+str(i-1)+'.amount_paid'
    form8416map['11. C Item '+str(i)] = 'expenses'+str(i-1)+'.date_paid'
    form8416map['11. D Item '+str(i)] = 'expenses'+str(i-1)+'.paid_to'
    form8416map['11. E Item '+str(i)] = 'expenses'+str(i-1)+'.person'
    

form534map = {    
    'Date of Claim': 'claim_date',
    'Vet Name': 'veteran_name',
    'Vet SSN': 'veteran_ssn',
    'Vet DOB': 'veteran_dob',
    'Male': 'veteran_gender.MALE',
    'Female': 'veteran_gender.FEMALE',
    'Die on Active Duty Y': 'active_duty_death.true',
    'Die on Active Duty N': 'active_duty_death.false',
    'Vet Service Number': 'veteran_service_number',
    'Date of Death': 'veteran_date_death',
    'Name': 'claimant_name',
    'Claimant SSN': 'claimant_ssn',
    'Surviving Spouse': 'relationship_to_veteran.SURVIVING SPOUSE',
    'Parent': 'relationship_to_veteran.PARENT',
    'Child': 'relationship_to_veteran.CHILD',
    'Custodian Filing for Child': 'relationship_to_veteran.CUSTODIAN FILING FOR CHILD',
    'Claimant DOB': 'claimant_dob',
    'Vet Y': 'claimant_veteran.true',
    'Vet N': 'claimant_veteran.false',
    'Claimant Address': 'mailing_address',
    'Claimant City': 'mailing_address_city',
    'Claimant State': 'mailing_address_state',
    'Claimant Zip': 'mailing_address_zip',
    'Phone Number': 'telephone',
    'Preferred Email': 'EMAIL',
    'Dependency': 'application_for.DEPENDENCY',
    'Survivors Pension': 'application_for.SURVIVORS PENSION',
    'Accrued Benefits': 'application_for.ACCRUED BENEFITS',
    'Another Name Y': 'veteran_other_name.true',
    'Another Name N': 'veteran_other_name.false',
    'Active Service Date': 'veteran_service_entry_date',
    'Branch of Service': 'branch_of_service',
    'Release Date': 'release_date',
    'Place of Last Separation': 'last_separation',
    'Title 10 Activation Y': 'veteran_active_duty.true',
    'Title 10 Activation N': 'veteran_active_duty.false',
    'POW Y': 'pow.true',
    'POW N': 'pow.false',
    'Year Married': 'veteran_marriages.times_married',
    'Date of Marriage 1': 'veteran_marriages.details0.date_of_marriage',
    'To Whom Married 1': 'veteran_marriages.details0.whom_married',
    'Type of Marriage 1': 'veteran_marriages.details0.type_of_marriage',
    'How Marriage Ended 1': 'veteran_marriages.details0.how_marriage_ended',
    'Date Marriage Ended 1': 'veteran_marriages.details0.date_ended',
    'Date of Marriage 2': 'veteran_marriages.details1.date_of_marriage',
    'To Whom Married 2': 'veteran_marriages.details1.whom_married',
    'Type of Marriage 2': 'veteran_marriages.details1.type_of_marriage',
    'How Marriage Ended 2': 'veteran_marriages.details1.how_marriage_ended',
    'Date Marriage Ended 2': 'veteran_marriages.details1.date_ended',
    'Times Married': 'claimant_marriages.times_married',
    'Remarried Y': 'claimant_marriages.been_remarried.true',
    'Remarried N': 'claimant_marriages.been_remarried.false',
    'Claim Date of Marriage': 'claimant_marriages.details0.date_of_marriage',
    'Claim To Whom Married': 'claimant_marriages.details0.whom_married',
    'Claim Type of Marriage': 'claimant_marriages.details0.type_of_marriage',
    'Claim How Marriage Ended': 'claimant_marriages.details0.how_marriage_ended',
    'Claim Date Marriage Ended': 'claimant_marriages.details0.date_ended',
    '23 Y': 'children.true',
    '23 N': 'children.false',
    '24 Y': 'expecting_child.true',
    '24 N': 'expecting_child.false',
    '25 Y': 'live_with_veteran.true',
    '25 N': 'live_with_veteran.false',
    '27 Y': 'marriage_legally_not_valid.true',
    '27 N': 'marriage_legally_not_valid.false',
    '37 Y': 'housebound_aa.true',
    '37 N': 'housebound_aa.false',
    '38A Y': 'nursing_home.true',
    '38A N': 'nursing_home.false',
    '39 Y': 'dependent_ss_benefits.true',
    '39 N': 'dependent_ss_benefits.false',
    'SS Recip': 'ss_payments0.recepient',
    'Gross Monthly Amount': 'ss_payments0.amount',
    '41 Y': 'own_residence.true',
    '41N': 'own_residence.false',
    'Lot': 'residence_size',
    '42B Y': 'lot_part_sold.true',
    '42B N': 'lot_part_sold.false',
    '43A Y': 'other_income.true',
    '43A N': 'other_income.false',
    '43B Y': 'dependents_other_income.true',
    '43B N': 'dependents_other_income.false',
    '43C Y': 'dependents_assets_10k.true',
    '43C N': 'dependents_assets_10k.false',
    '43D Y': 'assets_transfer.true',
    '43D N': 'assets_transfer.false',
    '43E Y': 'yes_to_43a_d.true',
    '43E N': 'yes_to_43a_d.false',
    '44 Y': 'claiming_ume.true',
    '44 N': 'claiming_ume.false',
    '45A 1': 'expenses0.person',
    '45B 1': 'expenses0.paid_to',
    '45C 1': 'expenses0.purpose',
    '45D 1': 'expenses0.date_paid',
    '45F 1': 'expenses0.amount_paid',
    '45A 2': 'expenses1.person',
    '45B 2': 'expenses1.paid_to',
    '45C 2': 'expenses1.purpose',
    '45D 2': 'expenses1.date_paid',
    '45F 2': 'expenses1.amount_paid',
    'Checking': 'banking_info.account_type.CHECKING',
    'Savings': 'banking_info.account_type.SAVINGS',
    'Checking Account No': 'banking_info.account_no_1',
    'Savings Account No': 'banking_info.account_no_2',
    'Name of Financial Institution': 'banking_info.bank_name',
    'Routing Number': 'banking_info.routing',
    'Claimant Signature': 'claimants_signature',
    'Date Signed': 'date_signed'
}

form0966map = {
    'Date of Claim': 'entitlement_date'
}

deathcert_map = {
    'Decedent Legal Name': 'deceased_legal_name',
    'Sex': 'sex',
    'SSN': 'SSN',
    'Age': 'age',
    'DOB': 'DOB',
    'Birthplace': 'birthplace',
    'Residence State': 'residence_state',
    'County': 'county',
    'City or Town': 'city',
    'Street and Number': 'street_number',
    'Zip': 'zip_code',
    'Inside City Limits Y': 'inside_city.true',
    'Inside City Limits N': 'inside_city.false',
    'Surviving Spouse Name': 'suviving_spouse_name',
    'US Armed Forces Y': 'us_armed_forces.true',
    'US Armed Forces N': 'us_armed_forces.false',
    'Martial Status - M': 'marital_status.Married',
    'Martial Status - M but S': 'marital_status.Married, but separated',
    'Martial Status - W': 'marital_status.Widowed',
    'Martial Status - D': 'marital_status.Divorced',
    'Martial Status - NM': 'marital_status.Never Married',
    'Martial Status - U': 'marital_status.Unknown',
    "Father's Name": 'fathers_name',
    "Mother's Name": 'mothers_name',
    "Informant's Name": 'informants_name',
    'Relationship to Decedent': 'relationship',
    'Mailing Address': 'mailing_address',
    'Hopsital - Inpatient': 'place_of_death.hospital_death.Inpatient',
    'Hopsital - ER': 'place_of_death.hospital_death.Emergency Room',
    'Hopsital - D.O.A.': 'place_of_death.hospital_death.Dead on Arrival',
    'County of Death': 'place_of_death.county_of_death',
    'Method of Disposition - Burial': 'place_of_death.method_of_disposition.Burial',
    'Method of Disposition - Cremation': 'place_of_death.method_of_disposition.Cremation',
    'Method of Disposition - Donation': 'place_of_death.method_of_disposition.Donation',
    'Method of Disposition - Entombment': 'place_of_death.method_of_disposition.Entombment',
    'Method of Disposition - Removal from Statee': 'place_of_death.method_of_disposition.Removal from State', 
    'Location': 'place_of_death.location',
    'Method of Disposition - Other': 'place_of_death.method_of_disposition.Other', 
    'Name / Address Funeral Facility': 'place_of_death.funeral_facility_address',
    'Sig of Funeral Service Licensee': 'place_of_death.signature',
    '23. License Number': 'place_of_death.license_number',
    'Date Dead': 'person_certifying_death.date_dead',
    'Time': 'person_certifying_death.time_dead',
    'Sig Person Pronouncing': 'person_certifying_death.signature',
    '27. License Number': 'person_certifying_death.license_number',
    'Medical Examiner Y': 'person_certifying_death.medical_examiner_contacted.true',
    'Medical Examiner N': 'person_certifying_death.medical_examiner_contacted.false',
    'Cause of Death': 'person_certifying_death.cause_of_death0',
    'Due to 1': 'person_certifying_death.cause_of_death1',
    'Autopsy Y': 'person_certifying_death.autopsy_performed.true',
    'Autopsy N': 'person_certifying_death.autopsy_performed.false',
    'Pronouncing & Cert Phys': 'person_certifying_death.certifier.Proniuncing & Certifying physician',
    'Medical Examiner / Coroner': 'person_certifying_death.certifier.Medical Examiner / Coroner',
    'Decedent Education <8th': 'funeral_director.decedents_education.8th grade or less', 
    'Decedent Race White': 'funeral_director.decedents_race.White', 
    'Decedent Hispanic Origin N': 'funeral_director.decedents_hispanic_origin.No, not Spanish/Hispanic/Latino',
    "Decedent Education Bachelor's": 'funeral_director.decedents_education.Bachelors degree',
    "Decedent's Occupation": 'funeral_director.decedents_occupation',
    'Kind of Business / Industry': 'funeral_director.kind_of_business'
}

#deathcert_map leftover
'''    
    'Date Signed'
    'Manner - Natural'
    'Manner - Homicide'
    'Tobacco Y'
    'Tabacco P'
    Manner - Accident
    Manner - Pending Investigation
    Tabacco N
    Tabacco U
    Manner - Suicide
    Manner - Unknown
    Certifying Phys
    'Place of Disposition'
    'Decedent Race Black AA'
    'Decedent Race American Indian Alaska Native'
    'Decedent Education 9-12th'
    'Decedent Race Asian Indian'
    'Decedent Education High/GED'
    'Decedent Race Filipino'
    'Decedent Race Chinese'
    'Decedent Education Some College'
    'Decedent Hispanic Origin Y Mexican'
    'Decedent Race Japanese'
    'Decedent Education Associate'
    'Decedent Hispanic Origin Puerto Rican'
    'Decedent Race Korean'
    'Decedent Race Vietnamese'
    'Decedent Hispanic Origin Y Cuban'
    'Decedent Race Other Asian'
    'Decedent Race Native Hawaiian'
    'Decedent Race Guamanian Chamorro'
    "Decedent Education Master's"
    'Decedent Hispanic Origin Y Other'
    'Decedent Race Samoan'
    'Decedent Race Other Pacific Islander'
    'Decedent Education PhD'
    'Decedent Race Other Specify'
'''

form2680map = {
    'Vet Name': 'veteran_name',
    'Vet M': 'veteran_gender.MALE',
    'Vet Female': 'veteran_gender.FEMALE', 
    'Vet DOB Month': 'veteran_dob',
    'Veteran SSN': 'veteran_ssn',
    'VA File Number': 'va_file_number',
    'Vet Service Number': 'veteran_service_number',
    'Claimant Name': 'claimant_name',
    'Relationship Spouse': 'relationship_to_veteran.Spouse',
    'Relationship Self': 'relationship_to_veteran.Self', 
    'Claimant SSN': 'claimant_ssn',
    'Claimant Home Address': 'mailing_address',
    'Claimant City': 'mailing_address_city',
    'Claimant State': 'mailing_address_state',
    'Claimant Zip Code': 'mailing_address_zip',
    'Special Monthly Comp': 'benefit_claimed',
    'Date of Examination': 'date_of_exam',
    'Claimant Hospitalized Y': 'claimant_hospitalized.true',
    'Claimant Hospitalized N': 'claimant_hospitalized.false',
    'Complete Diag': 'complete_diagnosis',
    'Age': 'age',
    'Estimated LBS': 'weight',
    'Feet': 'height_feet',
    'Inches': 'height_inches',
    'Gait': 'gait',
    'Restrict Activities': 'disabilities_restrict_activities',
    'Feed Himself Y': 'feed_oneself.true', 
    'Feed Himself N': 'feed_oneself.false',
    'Own Meals Y': 'prepare_meals.true',
    'Own Meals N': 'prepare_meals.false',
    'Own Meals Line 1': 'prepare_meals_explanation',
    'Bathing Y': 'assistance_bathing.true',
    'Bathing N': 'assistance_bathing.false',
    'Bathing Line 1': 'assistance_bathing_explanation',
    'Legally Blind Y': 'legally_blind.true',
    'Legally Blind N': 'legally_blind.false',
    'Med Management Y': 'medication_management.true',
    'Med Management N': 'medication_management.false',
    'Med Management Line 1': 'medication_management_explanation',
    'Mental Capacity Y': 'manage_payments.true',
    'Mental Capacity N': 'manage_payments.false',
    '33': 'posture',
    '34 Line 1': 'restrictions_grip_movements',
    '35': 'restrictions_motion',
    '36': 'restrictions_spine',
    '37': 'question_37',
    '38': 'question_38',
    '39 Y': 'question_39',
    'Printed Name Phys': 'name_of_physician',
    'Sig Phys': 'signature',
    'Date Signed': 'date_signed',
    'National Provider Identity': 'npi',
    'Medical Facility Phone Number': 'telephone',
    'Name of Medical Facility': 'name_of_facility',
    'Address of Medical Facility': 'address_of_facility',
}

award_data = [{'award_date': '12/20',
  'ss_monthly_income_monthly': '8598',
  'total_income': '8958',
  'SMIB_monthly': '144.6',
  'SMIB_annual': '1732.2',
  'PMI_monthly': '100',
  'PMI_annual': '1200',
  'total_meds': '2935',
  'less_deductible': '696',
  'net_meds': '2239',
  'IVAP': '6719',
  'MAPR': '13931',
  'monthly_rate': '601'},
 {'award_date': '2/21',
  'ss_monthly_income_monthly': '8598',
  'total_income': '8958',
  'SMIB_monthly': '148.5',
  'SMIB_annual': '1782',
  'PMI_monthly': '100',
  'PMI_annual': '1200',
  'total_meds': '2982',
  'less_deductible': '696',
  'net_meds': '2286',
  'IVAP': '6672',
  'MAPR': '13931',
  'monthly_rate': '604'}]

#MAPs for further refining data
map_of_maps = {
    'VA 21P-527EZ': form527map,
    'SSN Inquiry Form': ssn_inquiry_map,
    'SSN Inquiry Form V2': ssn_inquiry_map,
    'Medical Expense Report VA 21P-8416 Dec 2021': form8416map,
    'VA 21P-534EZ': form534map,
    'VA 21-0966': form0966map,
    'US Standard Death Certificate': deathcert_map,
    'VA 21-2680': form2680map
}
array_conversion_list_map = {
    'VA 21P-527EZ': ['ss_payments', 'expenses', 'veteran_marriages.details', 'spouse_marriages.details'],
    'SSN Inquiry Form': ['monthly_benefit'],
    'SSN Inquiry Form V2': ['monthly_benefit'],
    'Medical Expense Report VA 21P-8416 Dec 2021': ['expenses'],
    'VA 21P-534EZ': ['veteran_marriages.details', 'claimant_marriages.details', 'ss_payments', 'expenses'],
    'VA 21-0966': [],
    'US Standard Death Certificate': ['person_certifying_death.cause_of_death'],
    'VA 21-2680': [],
    'response_payload': ['ss_inquiry']
}
field_concat_map = {
    'VA 21P-527EZ': [['mailing_address', 'mailing_address_city', 'mailing_address_state'], 
                     ['spouse_address', 'spouse_address_city', 'spouse_address_state', 'spouse_address_zip']],
    'SSN Inquiry Form': [],
    'SSN Inquiry Form V2': [],
    'Medical Expense Report VA 21P-8416 Dec 2021': [['mailing_address', 'mailing_address_city', 'mailing_address_state', 'mailing_address_zip']],
    'VA 21P-534EZ': [['mailing_address', 'mailing_address_city', 'mailing_address_state', 'mailing_address_zip']],
    'VA 21-0966': [],
    'US Standard Death Certificate': [],
    'VA 21-2680': [['mailing_address', 'mailing_address_city', 'mailing_address_state', 'mailing_address_zip']]
}
checkbox_conversion_map = {
    'VA 21P-527EZ': ['pow', 'special_pension', 'recently_hospitalized', 'employed', 'self_employed', 'nursing_home',
                    'spouse_veteran', 'live_with_spouse', 'previus_claim'],
    'SSN Inquiry Form': [],
    'SSN Inquiry Form V2': [],
    'Medical Expense Report VA 21P-8416 Dec 2021': [],
    'VA 21P-534EZ': ['active_duty_death', 'veteran_other_name', 'veteran_active_duty', 'pow', 'claimant_marriages.been_remarried', 
                     'children', 'expecting_child', 'live_with_veteran', 'marriage_legally_not_valid', 'housebound_aa', 'nursing_home', 
                     'dependent_ss_benefits', 'own_residence', 'lot_part_sold', 'other_income', 'dependents_other_income', 
                     'dependents_assets_10k', 'assets_transfer', 'yes_to_43a_d', 'claiming_ume'],
    'VA 21-0966': [],
    'US Standard Death Certificate': ['inside_city', 'us_armed_forces', 'person_certifying_death.autopsy_performed', 'person_certifying_death.medical_examiner_contacted'],
    'VA 21-2680': ['claimant_hospitalized', 'feed_oneself', 'prepare_meals', 'assistance_bathing', 'legally_blind', 'medication_management', 'manage_payments']
}
multi_choice_conv_map = {
    'VA 21P-527EZ': [['branch_of_service', 'army', 'navy', 'marine_corps', 'space_force', 'air_force', 'coast_guard'],
                    ['marital_status', 'married', 'divorced', 'widowed', 'never_married']],
    'SSN Inquiry Form': [],
    'SSN Inquiry Form V2': [],
    'Medical Expense Report VA 21P-8416 Dec 2021': [],
    'VA 21P-534EZ': [['veteran_gender', 'MALE', 'FEMALE'], 
                    ['relationship_to_veteran', 'SURVIVING SPOUSE', 'PARENT', 'CHILD', 'CUSTODIAN FILING FOR CHILD'],
                    ['application_for', 'DEPENDENCY', 'SURVIVORS PENSION', 'ACCRUED BENEFITS'],
                    ['banking_info.account_type', 'CHECKING', 'SAVINGS']],
    'VA 21-0966': [],
    'US Standard Death Certificate': [['marital_status', 'Married', 'Married, but separated', 'Widowed', 'Divorced', 'Never Married', 'Unknown'],
                                     ['place_of_death.hospital_death', 'Inpatient', 'Emergency Room', 'Dead on Arrival'],
                                     ['place_of_death.method_of_disposition', 'Burial', 'Cremation', 'Donation', 'Entombment', 'Removal from State', 'Other'],
                                     ['person_certifying_death.certifier', 'Proniuncing & Certifying physician', 'Medical Examiner / Coroner'],
                                     ['funeral_director.decedents_education', '8th grade or less', 'Bachelors degree'],
                                     ['funeral_director.decedents_race','White'],
                                     ['funeral_director.decedents_hispanic_origin', 'No, not Spanish/Hispanic/Latino']],
    'VA 21-2680': [['veteran_gender', 'MALE', 'FEMALE'], ['relationship_to_veteran', 'Spouse', 'Self']]
}
parse_date_map = {
    'VA 21P-527EZ': ['disabilities.date_began', 'veteran_service_entry_date', 'release_date', 'expenses.date_paid'],
    'SSN Inquiry Form': [],
    'SSN Inquiry Form V2': [],
    'Medical Expense Report VA 21P-8416 Dec 2021': ['expenses.date_paid'],
    'VA 21P-534EZ': [],
    'VA 21-0966': [],
    'US Standard Death Certificate': [],
    'VA 21-2680': []
}
search_date_map = {
    'VA 21P-527EZ': ['claim_date'],
    'SSN Inquiry Form': [],
    'SSN Inquiry Form V2': [],
    'Medical Expense Report VA 21P-8416 Dec 2021': [],
    'VA 21P-534EZ': [],
    'VA 21-0966': ['entitlement_date'],
    'US Standard Death Certificate': [],
    'VA 21-2680': []
}
response_paylod_key_map = {
    'VA 21P-527EZ': 'form527data',
    'SSN Inquiry Form': 'ss_inquiry0',
    'SSN Inquiry Form V2': 'ss_inquiry1',
    'Medical Expense Report VA 21P-8416 Dec 2021': 'form8416data',
    'VA 21P-534EZ': 'form534data',
    'VA 21-0966': 'form0966data',
    'US Standard Death Certificate': 'death_certificate_data',
    'VA 21-2680': 'form2680data'
}